CREATE TABLE [dbo].[Item]
(
	[Id] INT NOT NULL IDENTITY, 
    [Pago] BIT NOT NULL DEFAULT 0, 
    [Estado] BIT NOT NULL DEFAULT 0, 
    [Nota] NVARCHAR(50) NOT NULL, 
    [IdOrden] INT NOT NULL,
    [IdComida] INT NOT NULL, 
    CONSTRAINT FkItemOrden FOREIGN KEY (IdOrden) REFERENCES Orden(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FkItemComida FOREIGN KEY (IdComida) REFERENCES Comida(Id) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT PkItem PRIMARY KEY (Id),
    CONSTRAINT ChItemPago CHECK ((Pago = 0) OR (Pago = 1 AND Estado = 1))
)
