CREATE TABLE [dbo].[Orden]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FechaHora] DATETIME DEFAULT GETDATE() NOT NULL, 
    [IdMesa] INT NOT NULL,
    CONSTRAINT FkOrdenMesa FOREIGN KEY (IdMesa) REFERENCES Mesa (id) ON DELETE NO ACTION ON UPDATE CASCADE,
)
