CREATE TABLE [dbo].[Orden]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FechaHora] DATETIME DEFAULT GETDATE() NOT NULL, 
    [IdMesa] INT NULL,
    CONSTRAINT FkOrdenMesa FOREIGN KEY (IdMesa) REFERENCES Mesa (id) ON DELETE SET NULL ON UPDATE CASCADE,
)
